"""Crea catalogo.xlsx (catálogo curado de soluciones) y referencias_sector.xlsx (plantilla vacía)."""
import pandas as pd

V = "2026-10-02"
COLS = ["id", "necesidad", "nombre", "peldano", "tipo", "costo_cop_min", "costo_cop_max", "costo_texto",
        "prerrequisitos", "omitir_si", "descripcion", "fuente_url", "fecha_verificacion", "confianza", "advertencia"]


def r(id, nec, nombre, peldano, tipo, costo_texto, descripcion, url="", fecha=V, conf="media", adv="",
      pre="", omitir="", cmin=None, cmax=None):
    return dict(id=id, necesidad=nec, nombre=nombre, peldano=peldano, tipo=tipo, costo_cop_min=cmin,
                costo_cop_max=cmax, costo_texto=costo_texto, prerrequisitos=pre, omitir_si=omitir,
                descripcion=descripcion, fuente_url=url, fecha_verificacion=fecha, confianza=conf, advertencia=adv)


NV = "no verificado"
FILAS = [
    r("FAC-1", "FAC", "Facturación gratuita de la DIAN", 1, "gratuito", "Gratis",
      "Servicio web gratuito de la DIAN para generar facturas electrónicas; requiere internet y habilitación previa.",
      "https://www.dian.gov.co/impuestos/factura-electronica/facturacion-gratuita/Paginas/default.aspx",
      conf="alta", adv="Cubre la facturación. Confirma requisitos de habilitación en la DIAN.", omitir="factura_electronica", cmin=0, cmax=0),
    r("FAC-2", "FAC;CON", "Alegra (contabilidad y facturación en la nube)", 2, "pago",
      "Desde ~COP 45.000 hasta ~COP 165.000 al mes según plan",
      "Contabilidad, facturación electrónica, inventario y punto de venta según el plan.",
      "https://www.alegra.com/colombia/contabilidad/precios", conf="baja",
      adv="Las fuentes dan precios distintos (89.000 y 163.900 aparecen para planes pyme). Confirma en la página oficial.",
      omitir="contabilidad_software", cmin=45000, cmax=165000),
    r("FAC-3", "FAC;CON", "Siigo (Nube, Facturación, Nómina y POS por línea)", 2, "pago",
      "Desde ~COP 49.000 al mes; planes pyme ~COP 139.000 a 191.000 según la fuente",
      "Líneas de producto que se contratan por separado.", "https://www.siigo.com", conf="baja",
      adv="Precios tomados de guías comparativas, no del sitio oficial. Confirma antes de decidir.",
      omitir="contabilidad_software", cmin=49000, cmax=220000),
    r("CON-0", "CON", "Plantilla ordenada de ingresos y gastos en Excel o Google Sheets", 0, "gratuito", "Gratis",
      "Una tabla con fecha, tipo, categoría y monto. Es el mismo formato que usa esta herramienta y el primer paso antes de pagar un software.",
      conf="criterio experto", omitir="contabilidad_software", cmin=0, cmax=0),
    r("CON-4", "CON", "Contador o asesor contable externo", 4, "servicio", "Por cotizar (no se recopilaron tarifas)",
      "Subcontratar la contabilidad cuando el volumen supera lo que se puede llevar internamente.",
      fecha=NV, conf="sin verificar", adv="Pide 3 cotizaciones con alcance definido."),
    r("CLI-0", "CLI", "Hoja de cálculo de clientes", 0, "gratuito", "Gratis",
      "Una hoja con nombre, contacto, última compra y próxima acción. Es el prerrequisito de cualquier CRM.",
      conf="criterio experto", omitir="base_clientes", cmin=0, cmax=0),
    r("CLI-1", "CLI", "HubSpot CRM (plan gratuito)", 1, "gratuito", "Gratis; los límites cambian",
      "CRM con contactos, embudo de ventas y seguimiento de actividades.", "https://www.hubspot.com/products/crm",
      adv="Las guías de 2026 discrepan: unas indican contactos ilimitados y otras 1.000; el plan gratuito muestra la marca de HubSpot. Confirma en el sitio oficial.",
      pre="base_clientes", omitir="crm", cmin=0, cmax=0),
    r("CLI-2", "CLI", "Zoho CRM (plan gratuito)", 1, "gratuito", "Gratis (hasta 3 usuarios según guías)",
      "CRM básico con leads, contactos, tareas e informes.", "https://www.zoho.com/crm/",
      adv="Una guía indica que el plan gratuito no incluye automatización de flujos. Confirma en el sitio oficial.",
      pre="base_clientes", omitir="crm", cmin=0, cmax=0),
    r("CLI-3", "CLI", "CRM de pago de entrada (p. ej. Zoho Standard o HubSpot Starter)", 2, "pago",
      "Cerca de 14 EUR por usuario al mes (Zoho Standard) o 20 USD al mes por 2 usuarios (HubSpot Starter), según guías",
      "Solo cuando el plan gratuito ya se quedó corto.", conf="baja",
      adv="Precios tomados de guías, no de los sitios oficiales. Convierte a COP con la tasa del día.", pre="crm"),
    r("CAJ-0", "CAJ", "Hoja de caja semanal con saldo proyectado a 8 semanas", 0, "gratuito", "Gratis",
      "Entradas, salidas y saldo proyectado para anticipar huecos de caja y priorizar cobros.",
      conf="criterio experto", cmin=0, cmax=0),
    r("CAJ-1", "CAJ", "Radar de Caja (herramienta de este proyecto)", 1, "gratuito", "Gratis",
      "Proyecta la caja y simula escenarios a partir de tu Excel de ingresos y gastos.", conf="propia",
      adv="Prototipo; no es una predicción exacta.", pre="registra_ventas", cmin=0, cmax=0),
    r("DAT-0", "DAT", "Registro de ventas e inventario en Excel o Google Sheets", 0, "gratuito", "Gratis",
      "Registrar cada venta con fecha y valor, y el inventario básico.", conf="criterio experto",
      omitir="registra_ventas", cmin=0, cmax=0),
    r("DAT-1", "DAT", "Tablas dinámicas y un panel simple en Excel o Google Sheets", 1, "gratuito", "Gratis",
      "Ventas por mes, por producto y por cliente en una hoja.", conf="criterio experto",
      pre="registra_ventas", omitir="revisa_indicadores", cmin=0, cmax=0),
    r("DAT-2", "DAT", "Paneles con Looker Studio o Power BI (versiones gratuitas)", 2, "gratuito",
      "Versiones gratuitas; condiciones sin verificar", "Tableros conectados a tus hojas de cálculo.",
      fecha=NV, conf="sin verificar", adv="No se verificaron las condiciones actuales de las versiones gratuitas.",
      pre="registra_ventas;revisa_indicadores", cmin=0, cmax=0),
    r("DAT-3", "DAT", "Analítica avanzada o BI de pago", 4, "servicio", "Por cotizar",
      "Solo con datos ordenados de varios meses y alguien que los use.", fecha=NV, conf="sin verificar",
      pre="registra_ventas;revisa_indicadores;responsable_digital"),
    r("AUT-0", "AUT", "Documentar y simplificar el proceso antes de automatizar", 0, "gratuito", "Gratis",
      "Escribir los pasos, eliminar los innecesarios y recién ahí automatizar.", conf="criterio experto", cmin=0, cmax=0),
    r("AUT-1", "AUT", "Funciones nativas: plantillas, formularios y recordatorios en Sheets, Excel o correo", 1, "gratuito",
      "Gratis", "Resuelve muchas tareas repetitivas sin herramientas nuevas.", conf="criterio experto", cmin=0, cmax=0),
    r("AUT-2", "AUT", "Plataformas de automatización sin código (Make, Zapier u otras)", 3, "freemium",
      "Planes gratuitos limitados; de pago por volumen (no verificado)", "Conectan aplicaciones y automatizan flujos.",
      "https://sense-digital.co/blog/posts/2026-04-14-automatizacion-ia-pymes-colombia.html", fecha=NV, conf="baja",
      adv="Condiciones y precios no verificados en los sitios oficiales.", pre="responsable_digital"),
    r("AUT-3", "AUT", "Subcontratar un freelance o empresa de automatización", 4, "servicio",
      "Por cotizar (no se recopilaron tarifas)", "Útil cuando el proceso ya está documentado y no hay quién lo configure.",
      fecha=NV, conf="sin verificar", adv="Pide 3 cotizaciones por entregables; los datos y la configuración deben quedar a tu nombre."),
    r("SEG-1", "SEG", "Verificación en dos pasos, gestor de contraseñas y copia en la nube (opciones gratuitas)", 1, "gratuito",
      "Gratis", "Medidas básicas que reducen el riesgo de perder acceso o información.", conf="criterio experto",
      adv="Revisa las condiciones de cada servicio gratuito.", cmin=0, cmax=0),
    r("FOR-1", "FOR", "Chequeo Digital de MinTIC", 0, "gratuito", "Gratis (unos 25 minutos)",
      "Diagnóstico oficial de madurez digital con recomendaciones; complementa esta herramienta.",
      "https://chequeodigital.mintic.gov.co/", conf="alta", cmin=0, cmax=0),
    r("FOR-2", "FOR", "Cursos gratuitos (p. ej. HubSpot Academy)", 1, "gratuito", "Gratis",
      "Cursos en línea sobre ventas, CRM y marketing.", "https://academy.hubspot.com",
      adv="La cantidad de cursos proviene de una reseña; verifica.", cmin=0, cmax=0),
    r("FOR-3", "FOR", "Centros de Transformación Digital Empresarial (MinTIC e iNNpulsa)", 1, "servicio público",
      "Gratis según información de 2019 a 2021",
      "Diagnóstico, plan personalizado, capacitación y acompañamiento para mipymes.",
      "https://www.centrosdetransformaciondigital.gov.co", fecha="2019-2021", conf="baja",
      adv="Información de 2019 a 2021. Confirma si el centro de tu región sigue operando.", cmin=0, cmax=0),
    r("FOR-4", "FOR", "Asesoría o consultoría privada o universitaria", 4, "servicio", "Por cotizar",
      "Acompañamiento a la medida cuando lo gratuito no alcanza.", fecha=NV, conf="sin verificar",
      adv="Pide alcance, entregables y referencias."),
    r("IA-1", "IA", "Asistente de IA generativa en versión gratuita (ChatGPT, Gemini, Claude u otros)", 1, "gratuito",
      "Gratis", "Para redactar, resumir y ordenar ideas. Regla: no ingreses datos personales de clientes ni información confidencial.",
      adv="Los límites de los planes gratuitos cambian; confirma en cada sitio.", omitir="ia_gratuita", cmin=0, cmax=0),
    r("IA-2", "IA", "IA generativa de pago", 2, "pago", "Típicamente decenas de USD por usuario al mes (no verificado)",
      "Solo cuando el uso gratuito ya es constante y hay casos concretos.", fecha=NV, conf="baja",
      adv="Precios no verificados.", pre="ia_gratuita;registra_ventas"),
    r("CAN-0", "CAN", "Ficha gratuita en Google Maps y perfil de redes con horarios y catálogo", 0, "gratuito", "Gratis",
      "Hacer que tus clientes te encuentren: dirección, horarios, fotos, catálogo y un contacto directo.",
      conf="criterio experto", adv="Los pasos exactos de Google cambian; sigue la ayuda oficial del servicio.",
      omitir="presencia_digital", cmin=0, cmax=0),
    r("CAN-1", "CAN", "Venta y pago en línea (tienda, enlace de pago o pasarela)", 2, "pago", "Por cotizar (comisiones y planes varían)",
      "Recibir pedidos y pagos sin estar presente. Compara comisiones antes de elegir.", fecha=NV, conf="sin verificar",
      adv="No se verificaron tarifas. Pide cotización y confirma comisiones.", pre="presencia_digital;pagos_digitales",
      omitir="venta_en_linea"),
    r("PRO-0", "PRO", "Documentar en una página cada uno de tus 3 procesos principales", 0, "gratuito", "Gratis",
      "Quién hace qué, en qué orden y con qué herramientas. Es el paso previo a automatizar.",
      conf="criterio experto", omitir="procesos_documentados", cmin=0, cmax=0),
    r("PRO-1", "PRO", "Tablero de tareas gratuito (Trello, Notion, Google Tasks u otro)", 1, "gratuito", "Gratis (planes gratuitos con límites)",
      "Asignar y seguir tareas del equipo en un solo lugar.", conf="baja",
      adv="Los límites de los planes gratuitos no se verificaron; confirma en cada sitio.",
      pre="procesos_documentados", omitir="control_tareas", cmin=0, cmax=0),
    r("PRO-3", "PRO", "Integración de ventas, inventario y contabilidad", 3, "pago", "Por cotizar",
      "Conectar los sistemas para no digitar dos veces. Primero revisa si tu software actual ya lo permite.",
      fecha=NV, conf="sin verificar", adv="No se verificaron costos.", pre="contabilidad_software;registra_ventas",
      omitir="sistemas_integrados"),
    r("EST-0", "EST", "Plan digital de una página", 0, "gratuito", "Gratis",
      "Problema, herramienta, costo, responsable y cómo medirás el resultado.", conf="criterio experto",
      omitir="plan_digital", cmin=0, cmax=0),
    r("EST-1", "EST", "Chequeo Digital de MinTIC (autodiagnóstico gratuito)", 1, "servicio público", "Gratis",
      "Autodiagnóstico de madurez digital de unos 25 minutos; sirve como segunda opinión.",
      "https://chequeodigital.mintic.gov.co/", conf="alta", cmin=0, cmax=0),
    r("SEG-0", "SEG", "Autorización de tratamiento de datos personales (Ley 1581 de 2012)", 0, "gratuito", "Gratis",
      "Texto simple que informa qué datos recoges, para qué y cómo pueden retirarlos. Conserva la prueba.",
      "https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=49981", conf="media",
      adv="Esta herramienta no es asesoría legal; consulta a un abogado si manejas datos sensibles.",
      omitir="habeas_data", cmin=0, cmax=0),
    r("CLI-4", "CLI", "WhatsApp Business: catálogo, respuestas rápidas y etiquetas", 1, "gratuito", "Gratis",
      "Perfil de empresa con catálogo, mensajes de bienvenida y etiquetas para organizar clientes.",
      conf="media", adv="Confirme las funciones vigentes en la ayuda oficial de WhatsApp Business.", omitir="whatsapp_business", cmin=0, cmax=0),
    r("CLI-5", "CLI", "Encuesta breve de satisfacción y recompra con un formulario gratuito", 1, "gratuito", "Gratis",
      "Tres preguntas: qué tan satisfecho quedó, si volvería a comprar y qué mejoraría. Se registra el porcentaje de clientes que regresa.",
      conf="criterio experto", pre="base_clientes", omitir="mide_clientes", cmin=0, cmax=0),
    r("CON-1", "CON", "Cuenta bancaria exclusiva del negocio", 0, "gratuito", "Gratis o de bajo costo según la entidad",
      "Separar el dinero del negocio del personal para medir el resultado real. Compare costos de manejo entre entidades.",
      conf="criterio experto", omitir="cuenta_separada", cmin=0, cmax=0),
    r("CAJ-2", "CAJ", "Política de plazos de pago y recordatorios de cobro", 0, "gratuito", "Gratis",
      "Definir por escrito plazos de pago, enviar recordatorios antes del vencimiento y revisar la cartera cada semana.",
      conf="criterio experto", cmin=0, cmax=0),
    r("CAJ-3", "CAJ", "Conciliación bancaria mensual en hoja de cálculo", 0, "gratuito", "Gratis",
      "Comparar cada mes el extracto bancario con los registros propios y explicar las diferencias.",
      conf="criterio experto", omitir="concilia_bancos", cmin=0, cmax=0),
    r("CAN-2", "CAN", "Código QR o enlace de pago de su banco o billetera", 1, "gratuito", "Gratis o con comisión por transacción",
      "Habilitar el pago digital sin datáfono. Compare comisiones entre entidades.", fecha=NV, conf="baja",
      adv="Las comisiones varían según la entidad; confirme antes de elegir.", omitir="pagos_digitales", cmin=0, cmax=0),
    r("PRO-2", "PRO", "Tabla de roles y responsabilidades por persona", 0, "gratuito", "Gratis",
      "Una hoja con cada persona, sus responsabilidades y ante quién responde.", conf="criterio experto",
      omitir="roles_claros", cmin=0, cmax=0),
    r("EST-2", "EST", "Presupuesto digital mensual con tope y revisión trimestral", 0, "gratuito", "Gratis",
      "Definir cuánto se puede gastar por mes en herramientas, ligado a la capacidad de caja.", conf="criterio experto",
      pre="plan_digital", omitir="presupuesto_digital", cmin=0, cmax=0),
    r("EST-3", "EST", "Tablero de tres a cinco indicadores del retorno digital", 1, "gratuito", "Gratis",
      "Horas ahorradas, ventas atribuidas y costo mensual por herramienta, en una hoja de cálculo.", conf="criterio experto",
      pre="plan_digital", omitir="mide_resultados_digitales", cmin=0, cmax=0),
    r("EST-4", "EST", "Revisión trimestral de tres competidores o referentes", 0, "gratuito", "Gratis",
      "Revisar sus canales, precios publicados, reseñas y promociones para priorizar.", conf="criterio experto",
      omitir="vigila_competencia", cmin=0, cmax=0),
    r("FOR-5", "FOR", "Designar un responsable digital y un plan de formación anual", 0, "gratuito", "Gratis",
      "Asignar por escrito a una persona, con tiempo semanal reservado y metas de formación.", conf="criterio experto",
      omitir="responsable_digital", cmin=0, cmax=0),
    r("DAT-5", "DAT", "Decisión mensual apoyada en un dato", 0, "gratuito", "Gratis",
      "Elegir cada mes una decisión (precio, compra o promoción) y tomarla con una cifra del tablero.", conf="criterio experto",
      pre="revisa_indicadores", omitir="usa_datos_decisiones", cmin=0, cmax=0),
]

import re

REEMPLAZOS = [
    ("Radar de Caja (herramienta de este proyecto)", "Proyección de caja de Nexo (esta herramienta)"),
    ("Prototipo; no es una predicción exacta.", "Es una proyección de sensibilidad, no una predicción exacta."),
    ("Las guías de 2026 discrepan: unas indican contactos ilimitados y otras 1.000; el plan gratuito muestra la marca de HubSpot. Confirma en el sitio oficial.",
     "Los límites del plan gratuito varían según la fuente; confirme en el sitio oficial."),
    ("Una guía indica que el plan gratuito no incluye automatización de flujos. Confirma en el sitio oficial.",
     "El plan gratuito puede no incluir automatización de flujos; confirme en el sitio oficial."),
    ("Las fuentes dan precios distintos (89.000 y 163.900 aparecen para planes pyme). Confirma en la página oficial.",
     "Los precios varían según el plan; confirme en la página oficial."),
    ("Precios tomados de guías comparativas, no del sitio oficial. Confirma antes de decidir.",
     "Los precios son referenciales; confirme en el sitio oficial antes de decidir."),
    ("Precios no verificados.", "Precios por confirmar con el proveedor."),
    ("Condiciones y precios no verificados en los sitios oficiales.", "Confirme condiciones y precios en el sitio oficial."),
    ("No se verificaron costos.", "Costos por confirmar con el proveedor."),
    ("No se verificaron tarifas. Pide cotización y confirma comisiones.", "Solicite cotización y confirme las comisiones."),
    ("No se verificaron las condiciones actuales de las versiones gratuitas.", "Confirme las condiciones vigentes de las versiones gratuitas."),
    ("Los límites de los planes gratuitos no se verificaron; confirma en cada sitio.", "Confirme los límites de los planes gratuitos en cada sitio."),
    ("La cantidad de cursos proviene de una reseña; verifica.", "Verifique la oferta vigente de cursos."),
    ("Versiones gratuitas; condiciones sin verificar", "Versiones gratuitas; condiciones por confirmar"),
    ("(no verificado)", "(por confirmar)"),
    ("Por cotizar (no se recopilaron tarifas)", "Por cotizar"),
    ("Típicamente decenas de USD", "Habitualmente decenas de USD"),
    ("Pide 3 cotizaciones por entregables; los datos y la configuración deben quedar a tu nombre.",
     "Solicite tres cotizaciones por entregables; los datos y la configuración deben quedar a nombre de la empresa."),
    ("Pide 3 cotizaciones con alcance definido.", "Solicite tres cotizaciones con alcance definido."),
    ("Pide alcance, entregables y referencias.", "Solicite alcance, entregables y referencias."),
    ("Confirma si el centro de tu región", "Confirme si el centro de su región"),
    ("Confirma requisitos de habilitación en la DIAN.", "Confirme los requisitos de habilitación en la DIAN."),
    ("Compara comisiones antes de elegir.", "Compare las comisiones antes de elegir."),
    ("Primero revisa si tu software actual ya lo permite.", "Primero revise si su software actual ya lo permite."),
    ("Documentar en una página cada uno de tus 3 procesos principales", "Documentar en una página cada uno de los tres procesos principales"),
    ("Hacer que tus clientes te encuentren", "Hacer que los clientes puedan encontrar el negocio"),
    ("Sigue la ayuda oficial del servicio", "Siga la ayuda oficial del servicio"),
    ("sigue la ayuda oficial del servicio", "siga la ayuda oficial del servicio"),
    ("Una tabla con fecha", "Una tabla con fecha"),
    ("Es el mismo formato que usa esta herramienta y el primer paso antes de pagar un software.", "Es el mismo formato que usa esta herramienta y el primer paso antes de pagar un software."),
    ("Regla: no ingreses datos personales", "Regla: no ingrese datos personales"),
    ("confirma en cada sitio", "confirme en cada sitio"),
    ("Confirma en cada sitio", "Confirme en cada sitio"),
    ("confirma en el sitio oficial", "confirme en el sitio oficial"),
    ("Precios tomados de guías, no de los sitios oficiales. Convierte a COP con la tasa del día.",
     "Precios referenciales; convierta a COP con la tasa del día y confirme en el sitio oficial."),
    (" según guías", " (referencial)"),
    ("Revisa las condiciones de cada servicio gratuito.", "Revise las condiciones de cada servicio gratuito."),
    ("Texto simple que informa qué datos recoges, para qué y cómo pueden retirarlos. Conserva la prueba.",
     "Texto simple que informa qué datos se recogen, para qué y cómo pueden retirarse. Conserve la prueba de la autorización."),
    ("Esta herramienta no es asesoría legal; consulta a un abogado si manejas datos sensibles.",
     "Esta herramienta no es asesoría legal; consulte a un abogado si maneja datos sensibles."),
    ("responsable y cómo medirás el resultado.", "responsable y cómo se medirá el resultado."),
]


def formal(t):
    if not isinstance(t, str):
        return t
    for a, b in REEMPLAZOS:
        t = t.replace(a, b)
    t = re.sub(r"\bConfirma\b", "Confirme", t)
    t = re.sub(r"\bconfirma\b", "confirme", t)
    t = re.sub(r"\btus\b", "sus", t)
    t = re.sub(r"\btu\b", "su", t)
    t = re.sub(r"\bTu\b", "Su", t)
    return t


for _f in FILAS:
    for _c in ("nombre", "descripcion", "advertencia", "costo_texto"):
        _f[_c] = formal(_f[_c])

if __name__ == "__main__":
    pd.DataFrame(FILAS, columns=COLS).to_excel("catalogo.xlsx", index=False)
    pd.DataFrame(columns=["sector", "ano", "margen_operacional", "margen_neto", "endeudamiento",
                          "razon_corriente", "rotacion_deudores_dias", "fuente"]).to_excel("referencias_sector.xlsx", index=False)
    print(len(FILAS), "soluciones en el catálogo")
