"""Nexo Digital - cuestionario de diagnóstico (30 preguntas en 8 secciones).

Cada pregunta se responde con tres opciones: Sí (2), En parte (1) o No (0).
Cada una trae su lectura según la respuesta, la necesidad que alimenta y su prioridad base.
"""

RESP = {2: "Sí", 1: "En parte", 0: "No"}

SECCIONES = {
    "Facturación y contabilidad": dict(
        ayuda="Cómo factura la empresa y cómo registra y concilia su dinero.",
        bajo="La base administrativa todavía es frágil: sin facturación ordenada y registros confiables, cualquier inversión digital se apoya en información incompleta.",
        medio="La base administrativa funciona, aunque con vacíos. El siguiente avance consiste en cerrar los puntos pendientes y dejar la información lista para analizarla.",
        alto="La base administrativa es sólida: facturación, contabilidad y conciliación permiten tomar decisiones con información confiable."),
    "Clientes y relación": dict(
        ayuda="Cómo se conoce, atiende y se da seguimiento a los clientes.",
        bajo="La relación con los clientes depende de la memoria de las personas. Registrar los datos de contacto es el primer paso para vender de nuevo y medir la fidelidad.",
        medio="Existe una relación organizada con parte de los clientes. El avance consiste en sistematizar el seguimiento y medir si los clientes regresan.",
        alto="La relación con los clientes está sistematizada y medida, lo que permite anticipar compras y corregir fallas de servicio."),
    "Canales, pagos y automatización": dict(
        ayuda="Por dónde se encuentra, se compra y se paga, y qué tareas ya se hacen sin intervención manual.",
        bajo="Los canales de venta y de pago siguen siendo básicamente presenciales. Aparecer en internet y facilitar el pago digital amplía el alcance con muy poca inversión.",
        medio="Hay presencia y pagos digitales parciales. El avance consiste en completar el recorrido del cliente, desde que lo encuentra hasta que paga.",
        alto="El recorrido del cliente (encontrar, pedir y pagar) está habilitado en canales digitales y ya existen tareas automatizadas."),
    "Datos e información": dict(
        ayuda="Si la empresa registra sus ventas e inventario y si esa información orienta sus decisiones.",
        bajo="Sin registro sistemático de ventas e inventario no hay base para analizar nada. Es la brecha que más condiciona las demás.",
        medio="Se registran datos, pero todavía no se explotan del todo. Revisar pocos indicadores con regularidad ya cambia la calidad de las decisiones.",
        alto="Los datos se registran, se revisan y se usan para decidir: la empresa tiene la base necesaria para analítica más avanzada."),
    "Procesos y organización": dict(
        ayuda="Qué tan claro, escrito y coordinado está el trabajo interno.",
        bajo="El trabajo depende de personas concretas y de acuerdos verbales. Documentar lo esencial reduce errores y es indispensable antes de automatizar.",
        medio="Hay orden en una parte del trabajo. Falta consolidar procesos escritos, seguimiento de tareas y conexión entre herramientas.",
        alto="Los procesos están definidos, se les hace seguimiento y las herramientas se conectan entre sí, lo que facilita crecer sin perder control."),
    "Estrategia y liderazgo": dict(
        ayuda="Si lo digital responde a un plan, tiene presupuesto y se mide su resultado.",
        bajo="Las decisiones digitales se toman de forma aislada. Un plan breve, con presupuesto y un indicador de éxito, evita compras sin retorno.",
        medio="Existe una dirección parcial. Falta amarrar plan, presupuesto y medición para saber qué inversiones valen la pena.",
        alto="La transformación digital está dirigida: hay plan, presupuesto y medición del retorno, lo que permite escalar con criterio."),
    "Seguridad y datos personales": dict(
        ayuda="Protección de la información de la empresa y cumplimiento básico frente a los datos de clientes.",
        bajo="La información del negocio está expuesta a pérdida o acceso indebido y puede haber incumplimiento en el manejo de datos personales. Las medidas básicas son gratuitas.",
        medio="Hay medidas de protección, pero incompletas. Cerrar los vacíos restantes reduce notablemente el riesgo con poco esfuerzo.",
        alto="La información está protegida y el tratamiento de datos personales está respaldado por autorización de los titulares."),
    "Capacidades del equipo": dict(
        ayuda="Habilidades del equipo y responsabilidad asignada sobre lo digital.",
        bajo="Nadie tiene formación ni responsabilidad sobre lo digital. Sin personas que adopten las herramientas, la tecnología no se usa.",
        medio="Existe alguna capacidad instalada. Asignar un responsable y un plan de formación consolida lo avanzado.",
        alto="El equipo cuenta con formación reciente y un responsable claro, condiciones que favorecen la adopción sostenida de herramientas."),
}


def q(key, sec, texto, ayuda, nec, prio, si, parcial, no, req=(), norma=False):
    return dict(key=key, sec=sec, texto=texto, ayuda=ayuda, nec=nec, prio=prio, req=list(req), norma=norma,
                si=si, parcial=parcial, no=no)


PREGUNTAS = [
    # ---------------------------------------------------------------- Facturación y contabilidad
    q("factura_electronica", "Facturación y contabilidad", "¿Emite factura electrónica en todas sus ventas que lo requieren?",
      "La factura electrónica es obligatoria para la mayoría de los contribuyentes. Responda Sí si todas sus ventas obligadas se facturan así.",
      "FAC", 3,
      "Cumple con la facturación electrónica, base para cualquier análisis de ventas.",
      "Factura electrónicamente solo una parte de sus ventas: unifique el procedimiento para que todas queden registradas.",
      "No factura electrónicamente. La DIAN ofrece una solución gratuita; habilitarla es la prioridad administrativa más inmediata.", norma=True),
    q("contabilidad_software", "Facturación y contabilidad", "¿Lleva la contabilidad en un software contable y no solo en cuaderno o Excel?",
      "Un software contable permite obtener estados financieros y costos de forma confiable. Excel solo cuenta como 'En parte'.",
      "CON", 2,
      "La contabilidad está en un sistema, lo que facilita obtener estados financieros y costos.",
      "La contabilidad se lleva en hojas de cálculo. Funciona mientras el volumen sea bajo, pero conviene migrar a un sistema cuando aumenten las transacciones.",
      "Sin contabilidad ordenada es difícil conocer los costos y la rentabilidad reales. Empiece con una plantilla de ingresos y gastos antes de pagar un software."),
    q("cuenta_separada", "Facturación y contabilidad", "¿El negocio tiene una cuenta bancaria separada de las finanzas personales?",
      "Mezclar dinero personal y del negocio impide saber cuánto gana realmente la empresa.",
      "CON", 2,
      "Las finanzas del negocio están separadas de las personales, lo que permite medir el resultado real.",
      "Hay separación parcial. Mientras se mezclen gastos personales con los del negocio, los indicadores serán poco confiables.",
      "Al mezclar el dinero personal y el del negocio no es posible medir el resultado real. Abrir una cuenta exclusiva para el negocio es gratuito o de muy bajo costo."),
    q("concilia_bancos", "Facturación y contabilidad", "¿Concilia cada mes los movimientos bancarios con sus registros?",
      "Conciliar es comparar el extracto bancario con los registros propios para detectar diferencias, errores o cobros no reconocidos.",
      "CAJ", 2,
      "La conciliación mensual detecta errores y cobros no reconocidos a tiempo.",
      "Concilia de manera irregular. Fijar una fecha mensual evita que los errores se acumulen.",
      "Sin conciliación bancaria los errores y cobros no reconocidos pasan inadvertidos. Una conciliación mensual en hoja de cálculo es suficiente para comenzar.", req=["contabilidad_software"]),
    # ---------------------------------------------------------------- Clientes y relación
    q("base_clientes", "Clientes y relación", "¿Tiene una base de clientes con nombre y teléfono o correo?",
      "Una lista ordenada de clientes con datos de contacto, en cualquier archivo o sistema.",
      "CLI", 3,
      "Cuenta con una base de clientes, prerrequisito de cualquier estrategia de fidelización.",
      "La base de clientes existe pero está incompleta o dispersa en varios lugares. Consolídela en un solo archivo.",
      "Sin una base de clientes no puede volver a contactarlos ni medir si regresan. Es el prerrequisito de cualquier herramienta de clientes."),
    q("whatsapp_business", "Clientes y relación", "¿Atiende a sus clientes con WhatsApp Business o con un catálogo digital?",
      "WhatsApp Business permite catálogo, respuestas rápidas y etiquetas para organizar clientes. Es gratuito.",
      "CLI", 1,
      "Atiende por un canal profesional, con catálogo y respuestas organizadas.",
      "Usa WhatsApp, pero sin las funciones empresariales. Activar catálogo y respuestas rápidas mejora la atención sin costo.",
      "No cuenta con un canal digital organizado de atención. WhatsApp Business es gratuito y suele ser el canal de menor esfuerzo."),
    q("crm", "Clientes y relación", "¿Da seguimiento a sus clientes con un CRM o una hoja de seguimiento?",
      "Un CRM (o una hoja bien llevada) registra cada contacto, la última compra y la próxima acción.",
      "CLI", 2,
      "Hay seguimiento sistemático de clientes y oportunidades.",
      "El seguimiento es informal. Registrar última compra y próxima acción en una hoja ya aporta mucho valor.",
      "Tiene clientes registrados pero sin seguimiento sistemático. Un CRM gratuito o una hoja de seguimiento pueden cubrirlo sin gasto.", req=["base_clientes"]),
    q("mide_clientes", "Clientes y relación", "¿Mide cuántos clientes vuelven a comprar y qué tan satisfechos quedan?",
      "Por ejemplo, el porcentaje de clientes que compró de nuevo en los últimos 3 meses o una encuesta breve de satisfacción.",
      "CLI", 2,
      "Mide la fidelidad y la satisfacción, información clave para decidir dónde invertir.",
      "Mide de forma ocasional. Convertirlo en un indicador mensual permite ver tendencias.",
      "No mide si los clientes regresan ni si quedan satisfechos. Un indicador de recompra y una encuesta de tres preguntas son un buen comienzo.", req=["base_clientes"]),
    # ---------------------------------------------------------------- Canales, pagos y automatización
    q("pagos_digitales", "Canales, pagos y automatización", "¿Recibe pagos digitales (transferencia, billetera, datáfono o enlace de pago)?",
      "Cualquier medio de pago que no sea efectivo.",
      "CAN", 2,
      "Recibe pagos digitales, lo que reduce el manejo de efectivo y deja trazabilidad.",
      "Acepta pagos digitales solo en algunos casos. Ofrecerlos de forma visible en todos los puntos de venta mejora la conversión.",
      "Solo recibe efectivo, lo que limita las ventas y deja poca trazabilidad. Un código QR o una cuenta de transferencia rápida ya habilita el pago digital."),
    q("presencia_digital", "Canales, pagos y automatización", "¿Su negocio aparece en internet con horarios, ubicación y contacto (Google Maps, redes o página web)?",
      "Que un cliente nuevo pueda encontrar su negocio y contactarlo sin conocerlo de antemano.",
      "CAN", 2,
      "Los clientes nuevos pueden encontrar y contactar el negocio en internet.",
      "Hay presencia en internet, pero incompleta o desactualizada. Revise horarios, fotos y datos de contacto.",
      "Hoy un cliente nuevo no puede encontrar el negocio en internet. Crear la ficha gratuita en Google Maps y un perfil de redes es el paso más rentable."),
    q("venta_en_linea", "Canales, pagos y automatización", "¿Los clientes pueden hacer pedidos o compras en línea (tienda, catálogo con pedido o formulario)?",
      "Que el cliente pueda pedir y pagar sin necesidad de estar presente ni de llamar.",
      "CAN", 1,
      "Los clientes pueden comprar sin estar presentes, ampliando el horario y el alcance de la venta.",
      "Recibe pedidos por mensajes, pero sin un proceso ordenado. Un formulario o catálogo con pedido reduce errores.",
      "No hay venta en línea. Antes de invertir en una tienda, valide la demanda con catálogo y pedidos por mensajería.", req=["presencia_digital"]),
    q("automatiza_algo", "Canales, pagos y automatización", "¿Tiene al menos una tarea repetitiva automatizada (recordatorios, facturas recurrentes, respuestas automáticas)?",
      "Una tarea que antes hacía una persona a mano y hoy se ejecuta sola.",
      "AUT", 1,
      "Ya libera tiempo con tareas automatizadas.",
      "Hay automatización puntual. Identifique cuál es la tarea repetitiva que más horas consume y automatícela primero.",
      "Todas las tareas repetitivas se hacen a mano. Primero documente y simplifique el proceso; después automatice con funciones gratuitas.", req=["procesos_documentados"]),
    # ---------------------------------------------------------------- Datos e información
    q("registra_ventas", "Datos e información", "¿Registra cada venta con fecha y valor en un archivo o sistema?",
      "Un registro ordenado de ventas, aunque sea en Excel.",
      "DAT", 3,
      "Cuenta con un registro de ventas, la base de cualquier análisis.",
      "El registro de ventas existe pero tiene huecos. La información incompleta distorsiona los indicadores.",
      "Sin registro de ventas no hay base para analizar ni para usar inteligencia artificial. Es el primer escalón de la preparación digital."),
    q("inventario_registrado", "Datos e información", "¿Lleva el inventario en un archivo o sistema actualizado?",
      "Existencias de productos o materiales con entradas y salidas registradas.",
      "DAT", 2,
      "El inventario está controlado, lo que reduce faltantes y exceso de existencias.",
      "El inventario se actualiza de manera irregular. Un conteo periódico mantiene la información útil.",
      "Sin control de inventario aparecen faltantes, excesos y pérdidas que no se detectan. Una hoja con entradas y salidas ya mejora el control."),
    q("revisa_indicadores", "Datos e información", "¿Revisa indicadores del negocio al menos una vez al mes?",
      "Por ejemplo ventas, margen, gastos principales o clientes nuevos.",
      "DAT", 2,
      "Revisa indicadores con regularidad, lo que permite detectar desviaciones a tiempo.",
      "Revisa indicadores de manera esporádica. Fijar una reunión mensual de 30 minutos consolida el hábito.",
      "Registra datos pero no los usa. Revisar tres o cuatro indicadores al mes ya cambia las decisiones.", req=["registra_ventas"]),
    q("usa_datos_decisiones", "Datos e información", "¿Cambia precios, compras o promociones según lo que muestran los datos?",
      "Que una decisión concreta haya cambiado por una cifra y no solo por intuición.",
      "DAT", 1,
      "Las decisiones se apoyan en datos, no solo en la intuición.",
      "Algunas decisiones usan datos. Elija una decisión por mes (precio, compra o promoción) y tómela con una cifra.",
      "Aunque revisa indicadores, estos todavía no cambian sus decisiones. Defina una decisión mensual que dependa explícitamente de un dato.", req=["revisa_indicadores"]),
    # ---------------------------------------------------------------- Procesos y organización
    q("procesos_documentados", "Procesos y organización", "¿Tiene por escrito cómo se hacen sus tres procesos principales?",
      "Por ejemplo vender, entregar y cobrar. Basta una página por proceso.",
      "PRO", 2,
      "Los procesos clave están escritos, lo que facilita capacitar y automatizar.",
      "Algunos procesos están escritos y otros no. Complete los tres principales antes de pensar en automatizar.",
      "Los procesos no están escritos: no se puede automatizar ni delegar con seguridad lo que no está definido."),
    q("control_tareas", "Procesos y organización", "¿Asigna y hace seguimiento de las tareas del equipo en una herramienta o tablero?",
      "Un tablero (físico o digital) donde se vea quién hace qué y para cuándo.",
      "PRO", 1,
      "Las tareas están asignadas y visibles para todo el equipo.",
      "El seguimiento de tareas es parcial. Un tablero compartido con responsable y fecha evita olvidos.",
      "Las tareas se asignan de forma verbal, lo que genera olvidos y dependencia de una persona. Un tablero gratuito resuelve gran parte del problema.", req=["procesos_documentados"]),
    q("sistemas_integrados", "Procesos y organización", "¿Sus ventas, inventario y contabilidad se conectan entre sí sin digitar dos veces?",
      "Que la información de una herramienta pase a la otra sin copiarla a mano.",
      "PRO", 1,
      "La información fluye entre herramientas sin duplicar trabajo.",
      "La integración es parcial. Revise si su software actual permite importar o exportar datos antes de comprar otro sistema.",
      "Se digita la misma información en varios lugares, con riesgo de errores y pérdida de tiempo. Primero revise qué permite su software actual.", req=["contabilidad_software"]),
    q("roles_claros", "Procesos y organización", "¿Cada persona del equipo sabe qué responsabilidades tiene y ante quién responde?",
      "Roles y responsabilidades definidos, aunque sean pocos.",
      "PRO", 2,
      "Los roles están claros, lo que reduce reprocesos y conflictos.",
      "Los roles están definidos solo en parte. Una lista simple de responsabilidades por persona evita vacíos.",
      "Los roles no están definidos, lo que genera tareas sin dueño. Una tabla de responsabilidades por persona es el punto de partida."),
    # ---------------------------------------------------------------- Estrategia y liderazgo
    q("plan_digital", "Estrategia y liderazgo", "¿Cuenta con un plan digital escrito, aunque sea de una página?",
      "Qué se quiere lograr con lo digital, con qué herramientas, cuánto costará y cómo se medirá.",
      "EST", 2,
      "Las decisiones digitales responden a un plan.",
      "Hay ideas claras pero no escritas. Páselas a una página con objetivo, herramienta, costo y medida de éxito.",
      "Sin plan, las compras de tecnología son decisiones sueltas. Una página con objetivo, herramienta, costo y medida de éxito basta para comenzar."),
    q("presupuesto_digital", "Estrategia y liderazgo", "¿Tiene definido un presupuesto mensual para herramientas digitales?",
      "Un tope mensual que la empresa se compromete a no superar.",
      "EST", 1,
      "Existe un tope de gasto digital, que protege la caja.",
      "El presupuesto digital es informal. Defina un tope mensual y revíselo cada trimestre.",
      "Sin un presupuesto definido es fácil acumular suscripciones sin uso. Defina un tope mensual conservador, ligado a su capacidad de caja.", req=["plan_digital"]),
    q("mide_resultados_digitales", "Estrategia y liderazgo", "¿Mide el retorno de lo que invierte en herramientas digitales?",
      "Horas ahorradas, ventas atribuidas o errores evitados frente a lo que cuesta cada herramienta.",
      "EST", 1,
      "Mide el retorno de sus inversiones digitales, lo que permite escalar con criterio.",
      "Hay mediciones parciales. Defina un indicador por herramienta y revíselo cada trimestre.",
      "No mide el retorno de lo que ya usa. Defina un indicador por herramienta (horas ahorradas o ventas atribuidas) y revíselo cada trimestre.", req=["plan_digital"]),
    q("vigila_competencia", "Estrategia y liderazgo", "¿Revisa con regularidad qué hacen digitalmente sus competidores o referentes del sector?",
      "Una revisión trimestral de tres competidores: canales, precios publicados, reseñas y promociones.",
      "EST", 1,
      "Conoce el entorno digital de su sector, lo que ayuda a priorizar.",
      "La revisión de competidores es ocasional. Una revisión trimestral de tres referentes es suficiente.",
      "No conoce qué hacen sus competidores en canales digitales. Una revisión trimestral de tres referentes aporta ideas sin costo."),
    # ---------------------------------------------------------------- Seguridad y datos personales
    q("backup_nube", "Seguridad y datos personales", "¿Sus archivos importantes tienen copia de seguridad en la nube o en otro lugar?",
      "Facturas, contabilidad, clientes y contratos respaldados fuera del equipo principal.",
      "SEG", 3,
      "La información crítica está respaldada y puede recuperarse ante una falla.",
      "Hay copias, pero no automáticas o no recientes. Programe una copia periódica y pruebe que se puede restaurar.",
      "Si el equipo falla o es robado, la información se pierde. Existen opciones gratuitas de copia en la nube."),
    q("dos_pasos", "Seguridad y datos personales", "¿Usa verificación en dos pasos en el correo y en la banca?",
      "Un segundo código además de la contraseña al iniciar sesión.",
      "SEG", 3,
      "Las cuentas principales están protegidas contra accesos indebidos.",
      "La verificación está activa solo en algunas cuentas. Extiéndala al correo principal y a la banca.",
      "Sin verificación en dos pasos, una contraseña filtrada basta para acceder a sus cuentas. Activarla es gratuito y toma minutos."),
    q("contrasenas", "Seguridad y datos personales", "¿Usa contraseñas distintas por servicio o un gestor de contraseñas?",
      "Evitar repetir la misma contraseña en varios servicios.",
      "SEG", 2,
      "Las contraseñas distintas limitan el daño si una se filtra.",
      "Repite algunas contraseñas. Cambie primero las del correo y la banca.",
      "Repetir contraseñas multiplica el riesgo. Un gestor de contraseñas gratuito resuelve el problema."),
    q("habeas_data", "Seguridad y datos personales", "¿Cuenta con autorización de sus clientes para tratar sus datos personales?",
      "La Ley 1581 de 2012 exige informar qué datos se recogen, para qué y cómo pueden retirarlos, y conservar la prueba de la autorización.",
      "SEG", 3,
      "El tratamiento de datos cuenta con autorización documentada, como exige la ley.",
      "Hay autorización solo para una parte de los clientes. Extiéndala a toda la base y conserve la prueba.",
      "Guarda datos de clientes sin autorización documentada, lo que la ley de protección de datos exige. Redacte una autorización simple y consérvela.", req=["base_clientes"], norma=True),
    # ---------------------------------------------------------------- Capacidades del equipo
    q("capacitacion", "Capacidades del equipo", "¿Alguien del equipo se capacitó en herramientas digitales en el último año?",
      "Cursos, talleres o formación autodirigida en herramientas útiles para el negocio.",
      "FOR", 2,
      "El equipo ha reforzado sus competencias digitales recientemente.",
      "La formación ha sido puntual. Un plan anual con metas simples sostiene el aprendizaje.",
      "Sin formación reciente, las herramientas existentes se subutilizan. Hay cursos gratuitos de buena calidad."),
    q("responsable_digital", "Capacidades del equipo", "¿Hay una persona responsable de los temas digitales de la empresa?",
      "Alguien con nombre y apellido que responda por las herramientas, los accesos y la mejora continua.",
      "FOR", 2,
      "Existe un responsable que da continuidad a lo digital.",
      "La responsabilidad existe de hecho, pero no está formalizada. Asígnela por escrito.",
      "Sin un responsable, lo digital no avanza o depende de quien tenga tiempo. Asigne a una persona, aunque sea una parte de su jornada."),
]

CLAVES = [p["key"] for p in PREGUNTAS]
POR_CLAVE = {p["key"]: p for p in PREGUNTAS}
assert len(PREGUNTAS) == 30 and len(set(CLAVES)) == 30
assert all(p["sec"] in SECCIONES for p in PREGUNTAS)


def por_seccion():
    out = {s: [] for s in SECCIONES}
    for p in PREGUNTAS:
        out[p["sec"]].append(p)
    return out


def lectura(p, v):
    return p["si"] if v == 2 else p["parcial"] if v == 1 else p["no"]
